language: php
sudo: false
dist: trusty
env:
    matrix:
        - SHAKE_AUTOLOADING_EXT=no
        - SHAKE_AUTOLOADING_EXT=yes
php:
    - 7.2
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
os:
    - windows
    - linux
before_script:
    - if [ "$SHAKE_AUTOLOADING_EXT" == "yes" ]; then sh -c "cd ext && phpize && ./configure && make && sudo make install"; fi
    - if [ "$SHAKE_AUTOLOADING_EXT" == "yes" ]; then echo "extension=php_shake_autoloading.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi
install:
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - php php-coveralls.phar --version
after_success:
    - travis_retry php php-coveralls.phar -v
before_script:
    - mkdir -p build/logs
    - ls -al
script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - ./vendor/bin/psalm
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
